home:
  path_link: "https://www.railstutorial.org/"
  path_link1: "naruto.jpeg"
help:
  path_link: "https://www.railstutorial.org/help"
  path_link2: "https://www.railstutorial.org/book"
about:
  path_link: "https://www.railstutorial.org/"
  path_link1: "https://www.learnenough.com/"
  path_link2: "https://www.railstutorial.org/book"
  path_link3: "https://screencasts.railstutorial.org/"
  path_link4: "https://rubyonrails.org/"
footer:
  path_link1: "https://www.railstutorial.org/"
  path_link2: "https://www.michaelhartl.com/"
  path_link3: "https://news.railstutorial.org/"
contact:
  path_link: "https://www.railstutorial.org/contac"
user:
  validate:
    name_max: 50
    email_max: 255
    pass_min: 6
users_helper:
  size: 80
